# Generated by Django 3.0.3 on 2020-02-20 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='issue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issue_label', to='base.Issue'),
        ),
    ]
