# Generated by Django 3.0.3 on 2020-02-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200220_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='updatd_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
